### ISSUE TITLE
Custom css prop for extending

### ISSUE THREAD

**Issue by malimichael** [jaakmusic/primitives#53]
I find myself reverting to inline styles via the `style` prop if the specified attribute is not available to a given primitive. For example:

```js
<Aside
        backgroundColor="white"
        padding={['20px']}
        position="fixed"
        style={{ boxShadow: '2px 0 30px 0 rgba(219, 219, 219, 0.5)' }} // no bueno
>
``` 

A current solution is to extend the given component adding on the required attributes. I propose an API that allows us to utilise the `css` helper provided by `styled-components`

```js
<Aside
        backgroundColor="white"
        padding={['20px']}
        position="fixed"
        css={css`
          box-shadow: 2px 0 30px 0 rgba(219, 219, 219, 0.5);
        `}
>
``` 

This way components can be extended inline. An added bonus to this approach is that we could use this prop to write component level media queries in pure css

**Comment by lukehedger** [comment]
@malimichael I really like this idea. Just saw an [interesting experiment](https://github.com/emotion-js/next) that made me think about this a little more. I think it'll be really useful in solving our media-queries issue too #51 

It might also be cool to be able to extend a primitive with 'utils' so that it _understands_ a non-standard prop (as opposed to having to create a new application-level primitive and add the util there).

Something like:
```jsx
<Aside
  boxShadow='2px 0 30px 0 rgba(219, 219, 219, 0.5)'
  util=['flexbox', 'shadow']
>
```

What do you think?

**Comment by lukehedger** [comment]
I like this idea from [Linaria](https://github.com/callstack/linaria) too - where you compose groups of _styles_:
```jsx
const title = css`
  text-transform: uppercase;
`

const container = css`
  padding: 3em;
`

const header = css`
  ${include(title)};

  font-family: ${fonts.heading};
  font-size: ${modularScale(2)};

  ${hiDPI(1.5)} {
    font-size: ${modularScale(2.5)}
  }
`

export default function Header() {
  return (
    <div {...styles(container)}>
      <h1 {...styles(header)} />
    </div>
  )
}
```
